# Generated by Django 3.0.5 on 2023-05-06 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=200)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_Admission_System.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Computer Science ', 'Computer Science '), ('Information Technology ', 'Information Technology '), ('Electronics and Telecommunication ', 'Electronics and Telecommunication '), ('Business and accounting', 'Business and accounting'), ('public Admin', 'public Admin'), ('LAW', 'LAW')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('nationality', models.CharField(max_length=250)),
                ('student_profile', models.ImageField(upload_to='images')),
                ('a_level_result', models.FileField(upload_to='')),
                ('o_level_result', models.FileField(upload_to='')),
                ('ple_result', models.FileField(upload_to='')),
                ('national_id', models.ImageField(null=True, upload_to='images')),
                ('teacher', models.CharField(max_length=100)),
                ('dom', models.CharField(choices=[('Boys hostel A', 'Boys hostel A'), ('Boys hostel B', 'Boys hostel B'), ('Boys hostel C', 'Boys hostel C'), ('Girls hostel A', 'Girls hostel A'), ('Girls hostel B', 'Girls hostel B'), ('Girls hostel C', 'Girls hostel C')], max_length=50)),
                ('Application_Status', models.TextField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('message', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
