# Generated by Django 3.0.5 on 2023-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students_Admission_System', '0003_remove_application_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
